platform :ios, '11.0'

target 'RNMagicScriptHostApplication' do
  use_frameworks!

  pod 'GLTFSceneKit'
  pod 'GrowingTextView', '0.7.1'

  target 'RNMagicScriptTests' do
    inherit! :search_paths
    pod 'Nimble'
    pod 'Quick'
    pod 'SwiftyMocky'
  end

end
